CREATE DATABASE pointofsaleDB;

CREATE TABLE workbench (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workbenchID VARCHAR(255),
    status TINYINT(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);